import { StyleSheet } from '@react-pdf/renderer'
import { pdfColors, scaleSize } from '@/lib/pdf-document-styles'
import { clampCardFontScale } from '@/lib/card-font-scale'

export const cardColors = {
  ...pdfColors,
  cream: '#faf6ef',
  creamBorder: '#e8dcc8',
  goldMuted: '#d4a574',
  ornament: '#1a4d7c',
} as const

export function createCardPdfStyles(compact = false, fontScaleInput = 1) {
  const fontScale = clampCardFontScale(fontScaleInput)
  const fs = (size: number) => scaleSize(size, fontScale)

  return StyleSheet.create({
    page: {
      backgroundColor: cardColors.cream,
      paddingVertical: compact ? 46 : 64,
      paddingHorizontal: 75,
      fontFamily: 'Helvetica',
      fontSize: fs(11),
      color: cardColors.text,
    },
    outerFrame: {
      flex: 1,
      borderWidth: 2,
      borderColor: cardColors.gold,
      padding: 3,
    },
    fixedOuterFrameTop: {
      position: 'absolute',
      top: compact ? 28 : 36,
      right: 40,
      left: 40,
      height: 2,
      backgroundColor: cardColors.gold,
    },
    fixedOuterFrameRight: {
      position: 'absolute',
      top: compact ? 28 : 36,
      right: 40,
      bottom: compact ? 28 : 36,
      width: 2,
      backgroundColor: cardColors.gold,
    },
    fixedOuterFrameBottom: {
      position: 'absolute',
      right: 40,
      bottom: compact ? 28 : 36,
      left: 40,
      height: 2,
      backgroundColor: cardColors.gold,
    },
    fixedOuterFrameLeft: {
      position: 'absolute',
      top: compact ? 28 : 36,
      bottom: compact ? 28 : 36,
      left: 40,
      width: 2,
      backgroundColor: cardColors.gold,
    },
    fixedInnerFrameTop: {
      position: 'absolute',
      top: compact ? 31 : 39,
      right: 43,
      left: 43,
      height: 1,
      backgroundColor: cardColors.creamBorder,
    },
    fixedInnerFrameRight: {
      position: 'absolute',
      top: compact ? 31 : 39,
      right: 43,
      bottom: compact ? 31 : 39,
      width: 1,
      backgroundColor: cardColors.creamBorder,
    },
    fixedInnerFrameBottom: {
      position: 'absolute',
      right: 43,
      bottom: compact ? 31 : 39,
      left: 43,
      height: 1,
      backgroundColor: cardColors.creamBorder,
    },
    fixedInnerFrameLeft: {
      position: 'absolute',
      top: compact ? 31 : 39,
      bottom: compact ? 31 : 39,
      left: 43,
      width: 1,
      backgroundColor: cardColors.creamBorder,
    },
    innerFrame: {
      flex: 1,
      borderWidth: 1,
      borderColor: cardColors.creamBorder,
      paddingVertical: compact ? 18 : 28,
      paddingHorizontal: 32,
      alignItems: 'stretch',
    },
    ornamentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: fs(10),
      width: '100%',
      alignSelf: 'center',
    },
    ornamentLine: {
      height: 1,
      flex: 1,
      backgroundColor: cardColors.goldMuted,
      maxWidth: scaleSize(80, fontScale),
    },
    ornamentDiamond: {
      width: fs(5),
      height: fs(5),
      backgroundColor: cardColors.gold,
      marginHorizontal: 8,
      transform: 'rotate(45deg)',
    },
    councilName: {
      fontSize: fs(13),
      fontFamily: 'Helvetica-Bold',
      color: cardColors.navyDark,
      textAlign: 'center',
      letterSpacing: 0.6,
      marginBottom: 4,
      alignSelf: 'center',
      maxWidth: scaleSize(420, fontScale),
    },
    councilAddress: {
      fontSize: fs(9),
      color: cardColors.textSoft,
      textAlign: 'center',
      lineHeight: 1.35,
      marginBottom: 2,
      alignSelf: 'center',
      maxWidth: scaleSize(420, fontScale),
    },
    councilPhones: {
      fontSize: fs(9),
      color: cardColors.textSoft,
      textAlign: 'center',
      lineHeight: 1.35,
      marginBottom: compact ? fs(10) : fs(14),
      alignSelf: 'center',
    },
    templateBadge: {
      backgroundColor: cardColors.navySoft,
      borderRadius: 12,
      paddingVertical: 3,
      paddingHorizontal: 12,
      marginBottom: compact ? fs(10) : fs(14),
      alignSelf: 'center',
    },
    templateBadgeText: {
      fontSize: fs(8),
      fontFamily: 'Helvetica-Bold',
      color: cardColors.navy,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    documentDateLine: {
      fontSize: fs(10),
      color: cardColors.text,
      marginBottom: fs(10),
      width: '100%',
      textAlign: 'right',
    },
    recipient: {
      fontSize: fs(10),
      color: cardColors.textSoft,
      marginBottom: 8,
      fontStyle: 'italic',
      width: '100%',
    },
    title: {
      fontSize: fs(20),
      fontFamily: 'Helvetica-Bold',
      color: cardColors.navyDark,
      lineHeight: 1.2,
      marginBottom: 6,
      width: '100%',
    },
    subtitle: {
      fontSize: fs(12),
      color: cardColors.navy,
      marginBottom: compact ? fs(10) : fs(14),
      width: '100%',
    },
    divider: {
      width: scaleSize(48, fontScale),
      height: 2,
      backgroundColor: cardColors.gold,
      marginBottom: compact ? fs(10) : fs(16),
      alignSelf: 'center',
    },
    bodyWrap: {
      width: '100%',
      marginBottom: compact ? fs(10) : fs(16),
    },
    body: {
      color: cardColors.text,
    },
    eventBox: {
      backgroundColor: cardColors.white,
      borderWidth: 1,
      borderColor: cardColors.creamBorder,
      borderRadius: 8,
      paddingVertical: fs(10),
      paddingHorizontal: 16,
      marginBottom: compact ? fs(10) : fs(16),
      width: '100%',
      maxWidth: scaleSize(360, fontScale),
      alignSelf: 'center',
      alignItems: 'center',
    },
    eventDate: {
      fontSize: fs(12),
      fontFamily: 'Helvetica-Bold',
      color: cardColors.navyDark,
      textAlign: 'center',
      marginBottom: 2,
    },
    eventTime: {
      fontSize: fs(11),
      color: cardColors.navy,
      textAlign: 'center',
    },
    eventLocation: {
      fontSize: fs(10),
      color: cardColors.textSoft,
      textAlign: 'center',
      marginTop: 4,
    },
    closing: {
      fontSize: fs(11),
      fontFamily: 'Helvetica-Bold',
      color: cardColors.gold,
      marginBottom: compact ? fs(12) : fs(20),
      width: '100%',
    },
    signaturesWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-around',
      width: '100%',
      marginTop: compact ? fs(18) : fs(26),
      marginBottom: compact ? fs(12) : fs(16),
      gap: fs(16),
    },
    signaturesWrapSingle: {
      justifyContent: 'center',
    },
    signatureBlock: {
      width: '30%',
      maxWidth: scaleSize(180, fontScale),
      alignItems: 'center',
      textAlign: 'center',
    },
    signatureBlockSingle: {
      width: '100%',
      maxWidth: scaleSize(260, fontScale),
    },
    signatureImage: {
      width: '100%',
      height: 36,
      objectFit: 'contain',
      objectPosition: 'center bottom',
      marginBottom: 2,
    },
    signatureImageSpacer: {
      width: '100%',
      height: 36,
    },
    signatureLine: {
      width: '100%',
      height: 1.25,
      backgroundColor: cardColors.text,
      marginTop: fs(4),
      marginBottom: fs(10),
    },
    signatureName: {
      fontSize: fs(10),
      fontFamily: 'Helvetica-Bold',
      color: cardColors.navyDark,
      textAlign: 'center',
    },
    signatureTitle: {
      fontSize: fs(9),
      color: cardColors.textSoft,
      textAlign: 'center',
      marginTop: 2,
    },
    sealWrap: {
      width: '100%',
      alignItems: 'flex-end',
      marginTop: 2,
      marginBottom: 6,
    },
    sealImage: {
      width: 112,
      height: 112,
      opacity: 0.7,
      transform: 'rotate(-7deg)',
    },
    footerOrnament: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
      marginTop: 'auto',
      width: '100%',
      alignSelf: 'center',
    },
    footerText: {
      fontSize: fs(10),
      fontFamily: 'Helvetica-Bold',
      color: cardColors.navyDark,
      textAlign: 'center',
      alignSelf: 'center',
    },
    footerSub: {
      fontSize: fs(8.5),
      color: cardColors.textMuted,
      textAlign: 'center',
      marginTop: 2,
      alignSelf: 'center',
    },
    continuationLabel: {
      fontSize: fs(9),
      color: cardColors.textMuted,
      fontStyle: 'italic',
      marginBottom: 8,
      width: '100%',
    },
  })
}

export type CardPdfStyles = ReturnType<typeof createCardPdfStyles>
